### ISSUE TITLE
Implement linting via `npm lint` for whole project

### ISSUE THREAD

**Issue by Schlomoh** [Vectreal/vectreal-core#19]
Use prettier and eslint for linting accross the whole project and code-style unification

**Comment by ryo-kozin** [comment]
Hi @Schlomoh,

I'd like to contribute to this issue by implementing the linting setup using Prettier and ESLint across the project. Could I go ahead and work on this?

Thank you!

**Comment by Schlomoh** [comment]
Hi there @ryo-kozin,

Awesome, that you want to contribute! 

For working with this repo locally see [our contributing guides](https://github.com/Vectreal/vectreal-core/blob/main/CONTRIBUTING.md) to get started. Feel free to fork, try things and once ready, create a PR against our origin/develop branch and then we'll see from there :)

**Comment by ryo-kozin** [comment]
Hi @Schlomoh,

Thank you for the guidance and encouragement! I will go through the contributing guide and start working on setting up linting for the project.

If I come across anything that could be improved beyond the scope of this issue, I’ll make sure to create additional issues as suggested.

Looking forward to contributing!

**Comment by ryo-kozin** [comment]
Hi @Schlomoh,

I've implemented the linting and formatting setup using Prettier and ESLint across the project as discussed in Issue #19. I have created this pull request to merge the changes into the develop branch.

Could you please review the changes when you have a moment and let me know if this aligns with the project requirements and your expectations? If there's anything that needs adjustment or if you have any suggestions, I'm happy to make the necessary changes.

Looking forward to your feedback!

Thank you!

**Comment by Schlomoh** [comment]
I added some feedback to the PR about linting :) #21
